export {Header} from "./Header/Header"
export {Footer} from "./Footer/Footer"
export {PreviewMovie} from "./PreviewMovie/PreviewMovie"
export { CollectionMovie } from "./CollectionMovie/CollectionMovie"
export { FilmContent } from "./FilmContent/FilmContent"