export {Header} from "./Header/Header"
export {Footer} from "./Footer/Footer"
export {HeroMovie} from "./HeroMovie/HeroMovie"
export { CollectionMovie } from "./CollectionMovie/CollectionMovie"
export { FilmContent } from "./FilmContent/FilmContent"
export { Raiting } from "./Raiting/Raiting"